/**
 * JSON Schema Draft 2020-12 Adapter
 *
 * Projects a CISMRoot to a JSON Schema document per Spec §11.1.
 * typeDistribution is NOT included in JSON Schema output.
 * No $ref or $defs — all schemas inlined (v1.3 simplification).
 */

import type { CISMRoot, SchemaNode, SchemaEdge } from "./types.js";

// ---------------------------------------------------------------------------
// Node → JSON Schema Mapping (§11.1 Mapping Rules)
// ---------------------------------------------------------------------------

function nodeToSchema(node: SchemaNode): Record<string, unknown> {
  switch (node.kind) {
    case "primitive":
      return primitiveToSchema(node);
    case "object":
      return objectToSchema(node);
    case "array":
      return arrayToSchema(node);
    case "union":
      return unionToSchema(node);
  }
}

function primitiveToSchema(node: SchemaNode): Record<string, unknown> {
  const pType = node.primitiveType ?? "string";

  // "null" type is already null; nullable doesn't add anything
  if (pType === "null") {
    return { type: "null" };
  }

  if (node.nullable) {
    return { type: [pType, "null"] };
  }

  return { type: pType };
}

function objectToSchema(node: SchemaNode): Record<string, unknown> {
  const properties: Record<string, unknown> = {};
  const required: string[] = [];

  for (const edge of node.properties ?? []) {
    properties[edge.name] = nodeToSchema(edge.target);
    if (edge.required) required.push(edge.name);
  }

  const result: Record<string, unknown> = { type: "object", properties };
  if (required.length > 0) result.required = required;

  return result;
}

function arrayToSchema(node: SchemaNode): Record<string, unknown> {
  const result: Record<string, unknown> = { type: "array" };
  if (node.itemType) {
    result.items = nodeToSchema(node.itemType);
  }
  return result;
}

function unionToSchema(node: SchemaNode): Record<string, unknown> {
  const members = (node.members ?? []).map(nodeToSchema);
  if (node.nullable) {
    members.push({ type: "null" });
  }
  return { oneOf: members };
}

// ---------------------------------------------------------------------------
// Public: JSON Schema Adapter
// ---------------------------------------------------------------------------

/**
 * Project CISMRoot to a JSON Schema Draft 2020-12 document.
 */
export function toJsonSchema(cism: CISMRoot): Record<string, unknown> {
  const schema: Record<string, unknown> = {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    title: "Inferred Schema",
    $comment: "Generated by BIBSS v1.3",
  };

  // $id from input hash if available
  if (cism.inputHash) {
    schema.$id = `urn:bibss:inferred:${cism.inputHash}`;
  }

  // Project the root node
  const rootSchema = nodeToSchema(cism.root);
  Object.assign(schema, rootSchema);

  return schema;
}
