/**
 * JSON Schema Adapter Tests (Phase 5.3)
 *
 * Tests JSON Schema Draft 2020-12 projection per Spec §11.1.
 */

import { deepStrictEqual, strictEqual, ok } from "node:assert";
import type { CISMRoot, SchemaNode, SchemaEdge } from "../src/kernel/types.js";
import { createDefaultConfig } from "../src/kernel/types.js";
import { toJsonSchema } from "../src/kernel/json-schema-adapter.js";

console.log("json-schema-adapter tests\n");

let passed = 0;
let failed = 0;

function test(name: string, fn: () => void): void {
  try {
    fn();
    console.log(`  \u2713 PASS: ${name}`);
    passed++;
  } catch (error) {
    console.error(`  \u2717 FAIL: ${name}`);
    console.error("   ", error instanceof Error ? error.message : String(error));
    failed++;
  }
}

// --- Helper ---

function buildCISM(root: SchemaNode, inputHash?: string): CISMRoot {
  return {
    version: "1.3",
    generatedAt: "2026-03-01T00:00:00.000Z",
    config: createDefaultConfig(),
    root,
    nodeIndex: new Map([[root.id, root]]),
    inputHash,
  };
}

function edge(name: string, target: SchemaNode, required = true): SchemaEdge {
  return { name, target, required, occurrences: 1, totalPopulation: 1 };
}

// --- Schema Metadata ---

test("includes $schema for Draft 2020-12", () => {
  const root: SchemaNode = { id: "#", kind: "object", occurrences: 1, properties: [] };
  const schema = toJsonSchema(buildCISM(root));
  strictEqual(schema.$schema, "https://json-schema.org/draft/2020-12/schema");
});

test("includes title and $comment", () => {
  const root: SchemaNode = { id: "#", kind: "object", occurrences: 1, properties: [] };
  const schema = toJsonSchema(buildCISM(root));
  strictEqual(schema.title, "Inferred Schema");
  strictEqual(schema.$comment, "Generated by BIBSS v1.3");
});

test("$id includes inputHash when present", () => {
  const root: SchemaNode = { id: "#", kind: "object", occurrences: 1, properties: [] };
  const schema = toJsonSchema(buildCISM(root, "abcdef1234567890"));
  strictEqual(schema.$id, "urn:bibss:inferred:abcdef1234567890");
});

test("$id is omitted when inputHash is not set", () => {
  const root: SchemaNode = { id: "#", kind: "object", occurrences: 1, properties: [] };
  const schema = toJsonSchema(buildCISM(root));
  strictEqual("$id" in schema, false);
});

// --- Primitive Mapping ---

test("primitive string → { type: 'string' }", () => {
  const root: SchemaNode = {
    id: "#", kind: "primitive", primitiveType: "string", occurrences: 1,
  };
  const schema = toJsonSchema(buildCISM(root));
  strictEqual(schema.type, "string");
});

test("primitive integer → { type: 'integer' }", () => {
  const root: SchemaNode = {
    id: "#", kind: "primitive", primitiveType: "integer", occurrences: 1,
  };
  const schema = toJsonSchema(buildCISM(root));
  strictEqual(schema.type, "integer");
});

test("primitive boolean → { type: 'boolean' }", () => {
  const root: SchemaNode = {
    id: "#", kind: "primitive", primitiveType: "boolean", occurrences: 1,
  };
  const schema = toJsonSchema(buildCISM(root));
  strictEqual(schema.type, "boolean");
});

test("primitive null → { type: 'null' }", () => {
  const root: SchemaNode = {
    id: "#", kind: "primitive", primitiveType: "null", nullable: true, occurrences: 1,
  };
  const schema = toJsonSchema(buildCISM(root));
  strictEqual(schema.type, "null");
});

test("nullable primitive → { type: ['<type>', 'null'] }", () => {
  const root: SchemaNode = {
    id: "#", kind: "primitive", primitiveType: "integer", nullable: true, occurrences: 10,
  };
  const schema = toJsonSchema(buildCISM(root));
  deepStrictEqual(schema.type, ["integer", "null"]);
});

// --- Object Mapping ---

test("object → { type: 'object', properties: {...} }", () => {
  const nameNode: SchemaNode = {
    id: "#/name", kind: "primitive", primitiveType: "string", occurrences: 1,
  };
  const root: SchemaNode = {
    id: "#", kind: "object", occurrences: 1,
    properties: [edge("name", nameNode)],
  };
  const schema = toJsonSchema(buildCISM(root));
  strictEqual(schema.type, "object");
  const props = schema.properties as Record<string, Record<string, unknown>>;
  deepStrictEqual(props.name, { type: "string" });
});

test("required properties listed in required array", () => {
  const a: SchemaNode = { id: "#/a", kind: "primitive", primitiveType: "string", occurrences: 1 };
  const b: SchemaNode = { id: "#/b", kind: "primitive", primitiveType: "integer", occurrences: 1 };
  const root: SchemaNode = {
    id: "#", kind: "object", occurrences: 1,
    properties: [edge("a", a, true), edge("b", b, false)],
  };
  const schema = toJsonSchema(buildCISM(root));
  deepStrictEqual(schema.required, ["a"]);
});

test("required is omitted when no required properties", () => {
  const a: SchemaNode = { id: "#/a", kind: "primitive", primitiveType: "string", occurrences: 1 };
  const root: SchemaNode = {
    id: "#", kind: "object", occurrences: 1,
    properties: [edge("a", a, false)],
  };
  const schema = toJsonSchema(buildCISM(root));
  strictEqual("required" in schema, false);
});

test("empty object → { type: 'object', properties: {} }", () => {
  const root: SchemaNode = { id: "#", kind: "object", occurrences: 1, properties: [] };
  const schema = toJsonSchema(buildCISM(root));
  deepStrictEqual(schema.properties, {});
});

// --- Array Mapping ---

test("array → { type: 'array', items: {...} }", () => {
  const item: SchemaNode = {
    id: "#/[]", kind: "primitive", primitiveType: "integer", occurrences: 5,
  };
  const root: SchemaNode = { id: "#", kind: "array", itemType: item, occurrences: 1 };
  const schema = toJsonSchema(buildCISM(root));
  strictEqual(schema.type, "array");
  deepStrictEqual(schema.items, { type: "integer" });
});

test("array with null itemType → { type: 'array' } (no items)", () => {
  const root: SchemaNode = { id: "#", kind: "array", itemType: null, occurrences: 1 };
  const schema = toJsonSchema(buildCISM(root));
  strictEqual(schema.type, "array");
  strictEqual("items" in schema, false);
});

// --- Union Mapping ---

test("union → { oneOf: [...members] }", () => {
  const m0: SchemaNode = {
    id: "#/|0", kind: "primitive", primitiveType: "integer", occurrences: 2,
  };
  const m1: SchemaNode = {
    id: "#/|1", kind: "object", occurrences: 1, properties: [],
  };
  const root: SchemaNode = {
    id: "#", kind: "union", members: [m0, m1], nullable: false, occurrences: 3,
  };
  const schema = toJsonSchema(buildCISM(root));
  const oneOf = schema.oneOf as Record<string, unknown>[];
  strictEqual(oneOf.length, 2);
  deepStrictEqual(oneOf[0], { type: "integer" });
  deepStrictEqual(oneOf[1], { type: "object", properties: {} });
});

test("nullable union → oneOf includes { type: 'null' } member", () => {
  const m0: SchemaNode = {
    id: "#/|0", kind: "primitive", primitiveType: "string", occurrences: 3,
  };
  const m1: SchemaNode = {
    id: "#/|1", kind: "object", occurrences: 2, properties: [],
  };
  const root: SchemaNode = {
    id: "#", kind: "union", members: [m0, m1], nullable: true, occurrences: 6,
  };
  const schema = toJsonSchema(buildCISM(root));
  const oneOf = schema.oneOf as Record<string, unknown>[];
  strictEqual(oneOf.length, 3);
  deepStrictEqual(oneOf[2], { type: "null" });
});

// --- Nested Structures ---

test("nested object → recursive projection", () => {
  const city: SchemaNode = {
    id: "#/address/city", kind: "primitive", primitiveType: "string", occurrences: 1,
  };
  const address: SchemaNode = {
    id: "#/address", kind: "object", occurrences: 1,
    properties: [edge("city", city)],
  };
  const root: SchemaNode = {
    id: "#", kind: "object", occurrences: 1,
    properties: [edge("address", address)],
  };
  const schema = toJsonSchema(buildCISM(root));
  const addressSchema = (schema.properties as Record<string, Record<string, unknown>>).address;
  strictEqual(addressSchema.type, "object");
  const citySchema = (addressSchema.properties as Record<string, Record<string, unknown>>).city;
  deepStrictEqual(citySchema, { type: "string" });
});

test("array of objects → array with object items", () => {
  const nameNode: SchemaNode = {
    id: "#/[]/name", kind: "primitive", primitiveType: "string", occurrences: 3,
  };
  const itemNode: SchemaNode = {
    id: "#/[]", kind: "object", occurrences: 3,
    properties: [edge("name", nameNode)],
  };
  const root: SchemaNode = { id: "#", kind: "array", itemType: itemNode, occurrences: 1 };
  const schema = toJsonSchema(buildCISM(root));
  strictEqual(schema.type, "array");
  const items = schema.items as Record<string, unknown>;
  strictEqual(items.type, "object");
  const nameSchema = (items.properties as Record<string, Record<string, unknown>>).name;
  deepStrictEqual(nameSchema, { type: "string" });
});

// --- typeDistribution NOT in output ---

test("typeDistribution is not present in JSON Schema output", () => {
  const root: SchemaNode = {
    id: "#", kind: "primitive", primitiveType: "string", occurrences: 5,
    typeDistribution: { string: 5 },
  };
  const schema = toJsonSchema(buildCISM(root));
  strictEqual("typeDistribution" in schema, false);
});

// --- Full Round-Trip ---

test("full round-trip: infer from sample data → project to JSON Schema", () => {
  // Simulate a CISM from: [{ name: "Alice", age: 30 }, { name: "Bob", age: 25 }]
  const nameNode: SchemaNode = {
    id: "#/[]/name", kind: "primitive", primitiveType: "string",
    occurrences: 2, typeDistribution: { string: 2 },
  };
  const ageNode: SchemaNode = {
    id: "#/[]/age", kind: "primitive", primitiveType: "integer",
    occurrences: 2, typeDistribution: { integer: 2 },
  };
  const itemNode: SchemaNode = {
    id: "#/[]", kind: "object", occurrences: 2,
    properties: [
      { name: "name", target: nameNode, required: true, occurrences: 2, totalPopulation: 2 },
      { name: "age", target: ageNode, required: true, occurrences: 2, totalPopulation: 2 },
    ],
  };
  const root: SchemaNode = { id: "#", kind: "array", itemType: itemNode, occurrences: 1 };
  const cism = buildCISM(root, "deadbeef");

  const schema = toJsonSchema(cism);

  strictEqual(schema.$schema, "https://json-schema.org/draft/2020-12/schema");
  strictEqual(schema.type, "array");
  const items = schema.items as Record<string, unknown>;
  strictEqual(items.type, "object");
  deepStrictEqual(items.required, ["name", "age"]);
  const props = items.properties as Record<string, Record<string, unknown>>;
  deepStrictEqual(props.name, { type: "string" });
  deepStrictEqual(props.age, { type: "integer" });
});

// Summary
console.log(`\n  ${passed} passed, ${failed} failed`);
if (failed > 0) {
  process.exit(1);
}
